layout_spectrum: 0.9317032
color:
  saturation: 0.2976391
  brandStrength: 0.8338954
  lightness: 0.188027
  brandColors:
    - '#E9EAE8'
    - '#161603'
    - '#5D656E'
    - '#FF5C01'
    - '#6E3901'
  rhythmicContrast: 0.6821248
typography_spectrum: 0.5067453
name: Why Fi
